// テンプレートの型定義
export interface ThumbnailTemplate {
  id: string;
  name: string;
  genre: 'simple' | 'cute' | 'cool' | 'stylish'; // ジャンルプロパティを追加
  initialText: string;
  initialTextColor: string;
  initialFontSize: string;
  initialImageSrc: string; // 必須に変更
  initialBackgroundImagePosition?: { x: number; y: number; width: number; height: number };
  initialCharacterImagePosition?: { x: number; y: number; width: number; height: number };
  initialTextPosition?: { x: number; y: number; width: number; height: number };
  supportedAspectRatios: string[];
}

// テンプレートの定義
export const templates: ThumbnailTemplate[] = [
  // --- simple ---
  {
    id: 'simple_1x1_001',
    name: 'シンプル 1:1 001',
    genre: 'simple',
    initialText: 'テキスト',
    initialTextColor: '#000000',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/simple/1x1/simple_1x1_001.png',
    supportedAspectRatios: ['1:1'],
  },
  {
    id: 'simple_1x1_002',
    name: 'シンプル 1:1 002',
    genre: 'simple',
    initialText: 'テキスト',
    initialTextColor: '#000000',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/simple/1x1/simple_1x1_002.png',
    supportedAspectRatios: ['1:1'],
  },
  {
    id: 'simple_1x1_003',
    name: 'シンプル 1:1 003',
    genre: 'simple',
    initialText: 'テキスト',
    initialTextColor: '#000000',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/simple/1x1/simple_1x1_003.jpg',
    supportedAspectRatios: ['1:1'],
  },
  {
    id: 'simple_1x1_004',
    name: 'シンプル 1:1 004',
    genre: 'simple',
    initialText: 'テキスト',
    initialTextColor: '#000000',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/simple/1x1/simple_1x1_004.jpg',
    supportedAspectRatios: ['1:1'],
  },
  {
    id: 'simple_1x1_005',
    name: 'シンプル 1:1 005',
    genre: 'simple',
    initialText: 'テキスト',
    initialTextColor: '#000000',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/simple/1x1/simple_1x1_005.jpg',
    supportedAspectRatios: ['1:1'],
  },
  {
    id: 'simple_1x1_006',
    name: 'シンプル 1:1 006',
    genre: 'simple',
    initialText: 'テキスト',
    initialTextColor: '#000000',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/simple/1x1/simple_1x1_006.jpg',
    supportedAspectRatios: ['1:1'],
  },
  {
    id: 'simple_1x1_007',
    name: 'シンプル 1:1 007',
    genre: 'simple',
    initialText: 'テキスト',
    initialTextColor: '#000000',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/simple/1x1/simple_1x1_007.jpg',
    supportedAspectRatios: ['1:1'],
  },
  {
    id: 'simple_4x3_001',
    name: 'シンプル 4:3 001',
    genre: 'simple',
    initialText: 'テキスト',
    initialTextColor: '#000000',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/simple/4x3/simple_4x3_001.jpg',
    supportedAspectRatios: ['4:3'],
  },
  {
    id: 'simple_4x3_002',
    name: 'シンプル 4:3 002',
    genre: 'simple',
    initialText: 'テキスト',
    initialTextColor: '#000000',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/simple/4x3/simple_4x3_002.jpg',
    supportedAspectRatios: ['4:3'],
  },
  {
    id: 'simple_4x3_003',
    name: 'シンプル 4:3 003',
    genre: 'simple',
    initialText: 'テキスト',
    initialTextColor: '#000000',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/simple/4x3/simple_4x3_003.jpg',
    supportedAspectRatios: ['4:3'],
  },
  {
    id: 'simple_4x3_004',
    name: 'シンプル 4:3 004',
    genre: 'simple',
    initialText: 'テキスト',
    initialTextColor: '#000000',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/simple/4x3/simple_4x3_004.jpg',
    supportedAspectRatios: ['4:3'],
  },
  {
    id: 'simple_4x3_005',
    name: 'シンプル 4:3 005',
    genre: 'simple',
    initialText: 'テキスト',
    initialTextColor: '#000000',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/simple/4x3/simple_4x3_005.jpg',
    supportedAspectRatios: ['4:3'],
  },
  {
    id: 'simple_9x16_001',
    name: 'シンプル 9:16 001',
    genre: 'simple',
    initialText: 'テキスト',
    initialTextColor: '#000000',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/simple/9x16/simple_9x16_001.jpg',
    supportedAspectRatios: ['9:16'],
  },
  {
    id: 'simple_9x16_002',
    name: 'シンプル 9:16 002',
    genre: 'simple',
    initialText: 'テキスト',
    initialTextColor: '#000000',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/simple/9x16/simple_9x16_002.jpg',
    supportedAspectRatios: ['9:16'],
  },
  {
    id: 'simple_9x16_003',
    name: 'シンプル 9:16 003',
    genre: 'simple',
    initialText: 'テキスト',
    initialTextColor: '#000000',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/simple/9x16/simple_9x16_003.jpg',
    supportedAspectRatios: ['9:16'],
  },
  {
    id: 'simple_9x16_004',
    name: 'シンプル 9:16 004',
    genre: 'simple',
    initialText: 'テキスト',
    initialTextColor: '#000000',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/simple/9x16/simple_9x16_004.jpg',
    supportedAspectRatios: ['9:16'],
  },
  {
    id: 'simple_16x9_001',
    name: 'シンプル 16:9 001',
    genre: 'simple',
    initialText: 'テキスト',
    initialTextColor: '#000000',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/simple/16x9/simple_16x9_001.png',
    supportedAspectRatios: ['16:9'],
  },
  {
    id: 'simple_16x9_002',
    name: 'シンプル 16:9 002',
    genre: 'simple',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/simple/16x9/simple_16x9_002.jpg',
    supportedAspectRatios: ['16:9'],
  },
  {
    id: 'simple_16x9_003',
    name: 'シンプル 16:9 003',
    genre: 'simple',
    initialText: 'テキスト',
    initialTextColor: '#000000',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/simple/16x9/simple_16x9_003.jpg',
    supportedAspectRatios: ['16:9'],
  },
  {
    id: 'simple_16x9_004',
    name: 'シンプル 16:9 004',
    genre: 'simple',
    initialText: 'テキスト',
    initialTextColor: '#000000',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/simple/16x9/simple_16x9_004.jpg',
    supportedAspectRatios: ['16:9'],
  },
  {
    id: 'simple_16x9_005',
    name: 'シンプル 16:9 005',
    genre: 'simple',
    initialText: 'テキスト',
    initialTextColor: '#000000',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/simple/16x9/simple_16x9_005.jpg',
    supportedAspectRatios: ['16:9'],
  },
  {
    id: 'simple_16x9_006',
    name: 'シンプル 16:9 006',
    genre: 'simple',
    initialText: 'テキスト',
    initialTextColor: '#000000',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/simple/16x9/simple_16x9_006.jpg',
    supportedAspectRatios: ['16:9'],
  },
  {
    id: 'simple_16x9_007',
    name: 'シンプル 16:9 007',
    genre: 'simple',
    initialText: 'テキスト',
    initialTextColor: '#000000',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/simple/16x9/simple_16x9_007.jpg',
    supportedAspectRatios: ['16:9'],
  },
  {
    id: 'simple_16x9_008',
    name: 'シンプル 16:9 008',
    genre: 'simple',
    initialText: 'テキスト',
    initialTextColor: '#000000',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/simple/16x9/simple_16x9_008.jpg',
    supportedAspectRatios: ['16:9'],
  },

  // --- cute ---
  {
    id: 'cute_1x1_001',
    name: 'かわいい 1:1 001',
    genre: 'cute',
    initialText: 'テキスト',
    initialTextColor: '#333333',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cute/1x1/cute_1x1_001.jpg',
    supportedAspectRatios: ['1:1'],
  },
  {
    id: 'cute_1x1_002',
    name: 'かわいい 1:1 002',
    genre: 'cute',
    initialText: 'テキスト',
    initialTextColor: '#333333',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cute/1x1/cute_1x1_002.jpg',
    supportedAspectRatios: ['1:1'],
  },
  {
    id: 'cute_1x1_003',
    name: 'かわいい 1:1 003',
    genre: 'cute',
    initialText: 'テキスト',
    initialTextColor: '#333333',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cute/1x1/cute_1x1_003.jpg',
    supportedAspectRatios: ['1:1'],
  },
  {
    id: 'cute_1x1_004',
    name: 'かわいい 1:1 004',
    genre: 'cute',
    initialText: 'テキスト',
    initialTextColor: '#333333',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cute/1x1/cute_1x1_004.jpg',
    supportedAspectRatios: ['1:1'],
  },
  {
    id: 'cute_1x1_005',
    name: 'かわいい 1:1 005',
    genre: 'cute',
    initialText: 'テキスト',
    initialTextColor: '#333333',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cute/1x1/cute_1x1_005.jpg',
    supportedAspectRatios: ['1:1'],
  },
  {
    id: 'cute_1x1_006',
    name: 'かわいい 1:1 006',
    genre: 'cute',
    initialText: 'テキスト',
    initialTextColor: '#333333',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cute/1x1/cute_1x1_006.jpg',
    supportedAspectRatios: ['1:1'],
  },
  {
    id: 'cute_4x3_001',
    name: 'かわいい 4:3 001',
    genre: 'cute',
    initialText: 'テキスト',
    initialTextColor: '#333333',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cute/4x3/cute_4x3_001.jpg',
    supportedAspectRatios: ['4:3'],
  },
  {
    id: 'cute_4x3_002',
    name: 'かわいい 4:3 002',
    genre: 'cute',
    initialText: 'テキスト',
    initialTextColor: '#333333',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cute/4x3/cute_4x3_002.jpg',
    supportedAspectRatios: ['4:3'],
  },
  {
    id: 'cute_4x3_003',
    name: 'かわいい 4:3 003',
    genre: 'cute',
    initialText: 'テキスト',
    initialTextColor: '#333333',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cute/4x3/cute_4x3_003.jpg',
    supportedAspectRatios: ['4:3'],
  },
  {
    id: 'cute_4x3_004',
    name: 'かわいい 4:3 004',
    genre: 'cute',
    initialText: 'テキスト',
    initialTextColor: '#333333',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cute/4x3/cute_4x3_004.jpg',
    supportedAspectRatios: ['4:3'],
  },
  {
    id: 'cute_4x3_005',
    name: 'かわいい 4:3 005',
    genre: 'cute',
    initialText: 'テキスト',
    initialTextColor: '#333333',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cute/4x3/cute_4x3_005.jpg',
    supportedAspectRatios: ['4:3'],
  },
  {
    id: 'cute_4x3_006',
    name: 'かわいい 4:3 006',
    genre: 'cute',
    initialText: 'テキスト',
    initialTextColor: '#333333',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cute/4x3/cute_4x3_006.jpg',
    supportedAspectRatios: ['4:3'],
  },
  {
    id: 'cute_9x16_001',
    name: 'かわいい 9:16 001',
    genre: 'cute',
    initialText: 'テキスト',
    initialTextColor: '#333333',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cute/9x16/cute_9x16_001.jpg',
    supportedAspectRatios: ['9:16'],
  },
  {
    id: 'cute_9x16_002',
    name: 'かわいい 9:16 002',
    genre: 'cute',
    initialText: 'テキスト',
    initialTextColor: '#333333',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cute/9x16/cute_9x16_002.jpg',
    supportedAspectRatios: ['9:16'],
  },
  {
    id: 'cute_9x16_003',
    name: 'かわいい 9:16 003',
    genre: 'cute',
    initialText: 'テキスト',
    initialTextColor: '#333333',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cute/9x16/cute_9x16_003.jpg',
    supportedAspectRatios: ['9:16'],
  },
  {
    id: 'cute_9x16_004',
    name: 'かわいい 9:16 004',
    genre: 'cute',
    initialText: 'テキスト',
    initialTextColor: '#333333',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cute/9x16/cute_9x16_004.jpg',
    supportedAspectRatios: ['9:16'],
  },
  {
    id: 'cute_9x16_005',
    name: 'かわいい 9:16 005',
    genre: 'cute',
    initialText: 'テキスト',
    initialTextColor: '#333333',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cute/9x16/cute_9x16_005.jpg',
    supportedAspectRatios: ['9:16'],
  },
  {
    id: 'cute_9x16_006',
    name: 'かわいい 9:16 006',
    genre: 'cute',
    initialText: 'テキスト',
    initialTextColor: '#333333',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cute/9x16/cute_9x16_006.jpg',
    supportedAspectRatios: ['9:16'],
  },
  {
    id: 'cute_16x9_001',
    name: 'かわいい 16:9 001',
    genre: 'cute',
    initialText: 'テキスト',
    initialTextColor: '#333333',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cute/16x9/cute_16x9_001.jpg',
    supportedAspectRatios: ['16:9'],
  },
  {
    id: 'cute_16x9_002',
    name: 'かわいい 16:9 002',
    genre: 'cute',
    initialText: 'テキスト',
    initialTextColor: '#333333',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cute/16x9/cute_16x9_002.jpg',
    supportedAspectRatios: ['16:9'],
  },
  {
    id: 'cute_16x9_003',
    name: 'かわいい 16:9 003',
    genre: 'cute',
    initialText: 'テキスト',
    initialTextColor: '#333333',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cute/16x9/cute_16x9_003.jpg',
    supportedAspectRatios: ['16:9'],
  },
  {
    id: 'cute_16x9_004',
    name: 'かわいい 16:9 004',
    genre: 'cute',
    initialText: 'テキスト',
    initialTextColor: '#333333',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cute/16x9/cute_16x9_004.jpg',
    supportedAspectRatios: ['16:9'],
  },
  {
    id: 'cute_16x9_005',
    name: 'かわいい 16:9 005',
    genre: 'cute',
    initialText: 'テキスト',
    initialTextColor: '#333333',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cute/16x9/cute_16x9_005.jpg',
    supportedAspectRatios: ['16:9'],
  },
  {
    id: 'cute_16x9_006',
    name: 'かわいい 16:9 006',
    genre: 'cute',
    initialText: 'テキスト',
    initialTextColor: '#333333',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cute/16x9/cute_16x9_006.jpg',
    supportedAspectRatios: ['16:9'],
  },
  {
    id: 'cute_16x9_007',
    name: 'かわいい 16:9 007',
    genre: 'cute',
    initialText: 'テキスト',
    initialTextColor: '#333333',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cute/16x9/cute_16x9_007.jpg',
    supportedAspectRatios: ['16:9'],
  },

  // --- cool ---
  {
    id: 'cool_1x1_001',
    name: 'クール 1:1 001',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/1x1/cool_1x1_001.jpg',
    supportedAspectRatios: ['1:1'],
  },
  {
    id: 'cool_1x1_002',
    name: 'クール 1:1 002',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/1x1/cool_1x1_002.jpg',
    supportedAspectRatios: ['1:1'],
  },
  {
    id: 'cool_1x1_003',
    name: 'クール 1:1 003',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/1x1/cool_1x1_003.jpg',
    supportedAspectRatios: ['1:1'],
  },
  {
    id: 'cool_1x1_004',
    name: 'クール 1:1 004',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/1x1/cool_1x1_004.jpg',
    supportedAspectRatios: ['1:1'],
  },
  {
    id: 'cool_1x1_005',
    name: 'クール 1:1 005',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/1x1/cool_1x1_005.jpg',
    supportedAspectRatios: ['1:1'],
  },
  {
    id: 'cool_1x1_006',
    name: 'クール 1:1 006',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/1x1/cool_1x1_006.jpg',
    supportedAspectRatios: ['1:1'],
  },
  {
    id: 'cool_1x1_007',
    name: 'クール 1:1 007',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/1x1/cool_1x1_007.jpg',
    supportedAspectRatios: ['1:1'],
  },
  {
    id: 'cool_1x1_008',
    name: 'クール 1:1 008',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/1x1/cool_1x1_008.jpg',
    supportedAspectRatios: ['1:1'],
  },
  {
    id: 'cool_1x1_009',
    name: 'クール 1:1 009',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/1x1/cool_1x1_009.jpg',
    supportedAspectRatios: ['1:1'],
  },
  {
    id: 'cool_4x3_001',
    name: 'クール 4:3 001',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/4x3/cool_4x3_001.jpg',
    supportedAspectRatios: ['4:3'],
  },
  {
    id: 'cool_4x3_002',
    name: 'クール 4:3 002',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/4x3/cool_4x3_002.jpg',
    supportedAspectRatios: ['4:3'],
  },
  {
    id: 'cool_4x3_003',
    name: 'クール 4:3 003',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/4x3/cool_4x3_003.jpg',
    supportedAspectRatios: ['4:3'],
  },
  {
    id: 'cool_4x3_004',
    name: 'クール 4:3 004',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/4x3/cool_4x3_004.jpg',
    supportedAspectRatios: ['4:3'],
  },
  {
    id: 'cool_4x3_005',
    name: 'クール 4:3 005',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/4x3/cool_4x3_005.jpg',
    supportedAspectRatios: ['4:3'],
  },
  {
    id: 'cool_4x3_006',
    name: 'クール 4:3 006',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/4x3/cool_4x3_006.jpg',
    supportedAspectRatios: ['4:3'],
  },
  {
    id: 'cool_4x3_007',
    name: 'クール 4:3 007',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/4x3/cool_4x3_007.jpg',
    supportedAspectRatios: ['4:3'],
  },
  {
    id: 'cool_4x3_008',
    name: 'クール 4:3 008',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/4x3/cool_4x3_008.jpg',
    supportedAspectRatios: ['4:3'],
  },
  {
    id: 'cool_4x3_009',
    name: 'クール 4:3 009',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/4x3/cool_4x3_009.jpg',
    supportedAspectRatios: ['4:3'],
  },
  {
    id: 'cool_9x16_001',
    name: 'クール 9:16 001',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/9x16/cool_9x16_001.jpg',
    supportedAspectRatios: ['9:16'],
  },
  {
    id: 'cool_9x16_002',
    name: 'クール 9:16 002',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/9x16/cool_9x16_002.jpg',
    supportedAspectRatios: ['9:16'],
  },
  {
    id: 'cool_9x16_003',
    name: 'クール 9:16 003',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/9x16/cool_9x16_003.jpg',
    supportedAspectRatios: ['9:16'],
  },
  {
    id: 'cool_9x16_004',
    name: 'クール 9:16 004',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/9x16/cool_9x16_004.jpg',
    supportedAspectRatios: ['9:16'],
  },
  {
    id: 'cool_9x16_005',
    name: 'クール 9:16 005',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/9x16/cool_9x16_005.jpg',
    supportedAspectRatios: ['9:16'],
  },
  {
    id: 'cool_9x16_006',
    name: 'クール 9:16 006',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/9x16/cool_9x16_006.jpg',
    supportedAspectRatios: ['9:16'],
  },
  {
    id: 'cool_9x16_007',
    name: 'クール 9:16 007',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/9x16/cool_9x16_007.jpg',
    supportedAspectRatios: ['9:16'],
  },
  {
    id: 'cool_16x9_001',
    name: 'クール 16:9 001',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/16x9/cool_16x9_001.jpg',
    supportedAspectRatios: ['16:9'],
  },
  {
    id: 'cool_16x9_002',
    name: 'クール 16:9 002',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/16x9/cool_16x9_002.jpg',
    supportedAspectRatios: ['16:9'],
  },
  {
    id: 'cool_16x9_003',
    name: 'クール 16:9 003',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/16x9/cool_16x9_003.jpg',
    supportedAspectRatios: ['16:9'],
  },
  {
    id: 'cool_16x9_004',
    name: 'クール 16:9 004',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/16x9/cool_16x9_004.jpg',
    supportedAspectRatios: ['16:9'],
  },
  {
    id: 'cool_16x9_005',
    name: 'クール 16:9 005',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/16x9/cool_16x9_005.jpg',
    supportedAspectRatios: ['16:9'],
  },
  {
    id: 'cool_16x9_006',
    name: 'クール 16:9 006',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/16x9/cool_16x9_006.jpg',
    supportedAspectRatios: ['16:9'],
  },
  {
    id: 'cool_16x9_007',
    name: 'クール 16:9 007',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/16x9/cool_16x9_007.jpg',
    supportedAspectRatios: ['16:9'],
  },
  {
    id: 'cool_16x9_008',
    name: 'クール 16:9 008',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/16x9/cool_16x9_008.jpg',
    supportedAspectRatios: ['16:9'],
  },
  {
    id: 'cool_16x9_009',
    name: 'クール 16:9 009',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/16x9/cool_16x9_009.jpg',
    supportedAspectRatios: ['16:9'],
  },
  {
    id: 'cool_16x9_010',
    name: 'クール 16:9 010',
    genre: 'cool',
    initialText: 'テキスト',
    initialTextColor: '#FFFFFF',
    initialFontSize: '4rem',
    initialImageSrc: '/templates/asset-creator/cool/16x9/cool_16x9_010.jpg',
    supportedAspectRatios: ['16:9'],
  },
];
